### ISSUE TITLE
本菜鸟安装boost失败了，希望您能发一份编译好的uabDec

### ISSUE THREAD

**Issue by musong0** [jspzyhl/AzurLane5.0-uabDec#1]
您好，本菜鸟安装boost失败了C1083（捂脸），希望您能发一份编译好的uabDec到我的邮箱，非常感谢。
我的邮箱：lanniant625@163.com 。
再次感谢，送您一朵小花花.jpg

**Comment by jspzyhl** [comment]
已发release
